In [12]:
print("Hello Workd")

Hello Workd


In [11]:
print(1+4)

5


In [10]:
print("The World")

The World


In [13]:
a = 10
b = 45

In [14]:
a+b=

SyntaxError: cannot assign to expression (<ipython-input-14-4be79a8e5344>, line 1)

In [15]:
x = a + b
print(x)

55


In [16]:
y = a * b
print(y)

450


In [17]:
import numpy as np
a = np.array([1,2,3])

In [18]:
a

array([1, 2, 3])

In [19]:
print(a)

[1 2 3]


In [1]:
import numpy as np

In [2]:
a = np.array([1,4,5])

In [3]:
a

array([1, 4, 5])

In [4]:
print(a)

[1 4 5]
