Train test split
Import libraries

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
#Generate some data we are going to split
a = np.arange(1,101)

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [5]:
#Split the data
train_test_split(a)

[array([46, 40,  7, 59, 69, 22,  1, 58, 16, 87, 39, 28, 27, 91, 64, 34, 44,
        85, 79, 83, 62, 26, 53, 70, 52, 55, 18, 20, 76, 93,  4, 35, 49, 41,
        32, 82, 73, 54, 94, 71, 97, 78, 21, 17, 92, 68, 61, 74,  8, 37, 77,
         9, 88, 63, 84, 45, 95, 29, 10, 13, 90, 86, 81, 57, 24, 96,  5, 31,
         2, 30, 19,  6, 60, 33, 14]),
 array([ 47,  15,   3,  80,  51,  23, 100,  56,  12,  65,  50,  72,  66,
         48,  99,  38,  67,  89,  36,  42,  75,  25,  43,  98,  11])]

In [12]:
a_train, a_test = train_test_split(a)

In [14]:
a_train.shape,a_test.shape

((75,), (25,))

In [15]:
a_train

array([ 94,  73,  77,   7,  39,  48,  68,  15,   9,  95,  34,  17,  89,
        28,  35,  88, 100,  47,  93,  33,  97,  76,  51,  16,  12,  72,
        21,  13,  31,  82,  96,  81,  69,  63,  92,  67,  30,  53,  83,
        25,  65,   2,  32,  54,  20,  85,  91,  42,  37,  86,  43,   4,
        38,  55,  11,  14,  74,  62,  40,  56,  80,  29,  26,  46,  90,
         6,  70,   5,  87,  23,   8,  61,  99,  64,  45])

In [16]:
a_test

array([22, 19, 50, 58, 78, 84, 66,  3, 71, 57, 36, 24, 98, 60, 27, 44, 59,
       18,  1, 10, 75, 41, 52, 79, 49])

In [17]:
# デフォルトで75：25になるが、テストデータが多いので、宣言時に割合を指定する
a_train, a_test = train_test_split(a,test_size=0.2)

a_train.shape,a_test.shape

((80,), (20,))

In [18]:
#データのシャッフルをFalseで無効に。通常はシャッフルするほうが好ましい。
a_train, a_test = train_test_split(a,test_size=0.2, shuffle=False)

a_train.shape,a_test.shape

((80,), (20,))

In [19]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [20]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [24]:
#コード実行時毎回ランダム生成されるので、指定する
#2つの配列を同時につくる→元のaのn項目と元のbのn項目の対応関係が維持できる
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size=0.2,random_state=365)

a_train.shape,a_test.shape

((80,), (20,))

In [25]:
a_train

array([ 25,  32,  99,  73,  91,  66,   3,  59,  94,   1,   8,  15,  90,
        54,  31,  20,  77,  82,  30,  35,  95,  42,  38,   7,  11,  50,
        21,  48,   2,  17,  10,  58,  68,  43,  41,  16,  88,  72,  79,
       100,  80,  39,  24,  86,  22,  23,  62,  76,  18,  47,  55,  26,
        60,  19,  71,  64,  51,  63,  65,  28,  12,  78,  13,  44,  75,
        87,  40,   4,  29,  49,  37,  57,  27,  74,   6,  45,  92,  34,
        53,  83])

In [26]:
a_test

array([ 9, 69, 81, 56, 33, 93, 84, 61, 46, 89, 85, 67, 97,  5, 70, 36, 98,
       96, 14, 52])

In [27]:
b_train

array([525, 532, 599, 573, 591, 566, 503, 559, 594, 501, 508, 515, 590,
       554, 531, 520, 577, 582, 530, 535, 595, 542, 538, 507, 511, 550,
       521, 548, 502, 517, 510, 558, 568, 543, 541, 516, 588, 572, 579,
       600, 580, 539, 524, 586, 522, 523, 562, 576, 518, 547, 555, 526,
       560, 519, 571, 564, 551, 563, 565, 528, 512, 578, 513, 544, 575,
       587, 540, 504, 529, 549, 537, 557, 527, 574, 506, 545, 592, 534,
       553, 583])

In [28]:
b_test

array([509, 569, 581, 556, 533, 593, 584, 561, 546, 589, 585, 567, 597,
       505, 570, 536, 598, 596, 514, 552])