In [1]:
import numpy as np

In [2]:
s = 5
s

5

In [3]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

In [5]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [6]:
type(s)

int

In [7]:
type(v)

numpy.ndarray

In [8]:
type(m)

numpy.ndarray

In [9]:
s_array = np.array(5)
s_array

array(5)

In [11]:
v.shape

(3,)

In [12]:
m.shape

(2, 3)

In [13]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [14]:
# テンソルの作成　行列の集まりと考えることができる

In [15]:
m1 = np.array([[5,12,6],[-3,0,14]])

In [16]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [17]:
m2 = np.array([[9,7,6],[1,34,0]])
m2

array([[ 9,  7,  6],
       [ 1, 34,  0]])

In [18]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  7,  6],
        [ 1, 34,  0]]])

In [19]:
t.shape

(2, 2, 3)

In [20]:
t_manual = np.array([[[5,23,45],[-3,0,14]],[[9,8,7],[1,4,33]]])
t_manual

array([[[ 5, 23, 45],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  4, 33]]])

In [21]:
# 足し算、引き算

In [22]:
m1=np.array([[5,12,6],[-3,0,14]])
m2=np.array([[9,8,7],[1,3,-5]])

In [23]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [25]:
m3 = np.array([[5,3],[-2,4]])
m4 = np.array([[7,-5],[3,8]])

In [26]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

In [27]:
m5 = np.array([[22.33,-4.73],[-203.14,1200.02],[4.22,234.1]])
m6 = np.array([[233,45],[44,6767],[232,454]])

In [28]:
m5-m6

array([[ -210.67,   -49.73],
       [ -247.14, -5566.98],
       [ -227.78,  -219.9 ]])

In [29]:
v2 = np.array([1,2,3,4,5])
v1 = np.array([5,4,3,2,1])

In [30]:
v1+v2

array([6, 6, 6, 6, 6])

In [31]:
v1-v2

array([ 4,  2,  0, -2, -4])

In [32]:
# Error

In [33]:
5+5

10

In [34]:
198-34

164

In [35]:
m1 = np.array([[5,12,6],[-3,0,14]])
m2 = np.array([[5,3],[-2,4]])

In [36]:
m2+m1

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [37]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([1,2,3])

In [38]:
v1+v2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [39]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [40]:
# 数学上はできないけど、プログラミング上で演算できる
m1 +1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [41]:
v1+3

array([4, 5, 6, 7, 8])

In [42]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [43]:
v1+np.array([1])

array([2, 3, 4, 5, 6])

In [44]:
# 転置

In [45]:
A = np.array([[5,12,6],[-3,0,14]])

In [46]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [47]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [48]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [49]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [50]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [51]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

In [52]:
s = np.array([5])
s

array([5])

In [53]:
s.T

array([5])

In [54]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [55]:
x.T

array([1, 2, 3])

In [56]:
x.shape

(3,)

In [57]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [59]:
x_reshaped.T

array([[1],
       [2],
       [3]])

In [60]:
# ドット積、スカラー積

In [61]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [62]:
np.dot(x,y)

np.int64(-66)

In [63]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [64]:
np.dot(u,v)

np.int64(18)

In [65]:
np.dot(5,6)

np.int64(30)

In [66]:
x

array([ 2,  8, -4])

In [67]:
5*x

array([ 10,  40, -20])

In [68]:
x*4

array([  8,  32, -16])

In [69]:
A  = np.array([[5,12,6],[-3,0,14]])
B = np.array([[2,-1],[8,0],[3,0]])

In [70]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [71]:
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [72]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])

In [74]:
C  = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])

In [75]:
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [76]:
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [77]:
np.dot(C,D)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])